#########################
#                       #
# Coded by KieranSlayer #
#                       #
#########################

#Color codes work with & so if u know the color u want just use & in front of it#

#Please do not remove '' As that will break the plugin #
 
Discord: '&2Our Discord :&4YOURDISCORDHERE'
#                                                             #
ServerIP: '&2Our ServerIP :&4YOURSERVERIPHERE'
#                                                             #
Facebook: '&2Our ServerIP :&4YOURFACEABOOKHERE'
#                                                             #
Twitter: '&2Our ServerIP :&4YOURTWITTERHERE'
#                                                             #
TeamSpeak: '&2Our ServerIP :&4YOURTeamSpeakHERE'