main: me.kieranslayer.sm.Main
version: 1.7
Author: KieranSlayer
name: SocialMediaPlugin
commands:
  Discord:
    usage: /<command>
    description: Give you discord link
    aliases: []
  ServerIP:
    usage: /<command>
    description: Give you Server IP
    aliases: [sip,server,ip]
  Website:
    usage: /<command>
    description: Give you discord link
    aliases: [wb]
  Facebook:
    usage: /<command>
    description: Give you discord link
    aliases: [fb]